# Generated by Django 5.1.4 on 2024-12-29 20:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_proyecto', models.CharField(choices=[('propuesta', 'Propuesta'), ('ejecucion', 'ejecucion'), ('standby', 'StandBy')], max_length=25, null=True)),
                ('id', models.CharField(max_length=25, unique=True)),
                ('pm', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('alcance', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'proyectos',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='AuditLogProyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('instance_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('old_data', models.TextField(blank=True, null=True)),
                ('new_data', models.TextField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log_proyectos',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.poll')),
            ],
        ),
        migrations.CreateModel(
            name='Prospecciones',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_prospeccion', models.CharField(choices=[('sondajes', 'Sondajes'), ('calicatas', 'Calicatas'), ('geofisica', 'Geofísica')], max_length=25)),
                ('id_prospeccion', models.CharField(max_length=25, unique=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('coordenada_este', models.CharField(blank=True, max_length=6, null=True)),
                ('coordenada_norte', models.CharField(blank=True, max_length=7, null=True)),
                ('elevacion', models.IntegerField(blank=True, null=True)),
                ('profundidad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('verificacion_puntos', models.CharField(blank=True, choices=[('realizado', 'Realizado'), ('no_realizado', 'No Realizado')], max_length=25, null=True)),
                ('plataforma', models.CharField(blank=True, choices=[('realizado', 'Realizado'), ('no_realizado', 'No Realizado')], max_length=25, null=True)),
                ('inclinacion', models.IntegerField(blank=True, null=True)),
                ('diametro', models.IntegerField(blank=True, null=True)),
                ('tapado', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=25, null=True)),
                ('contratista', models.CharField(blank=True, max_length=100, null=True)),
                ('marca_maquina1', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo_maquina1', models.CharField(blank=True, max_length=50, null=True)),
                ('ppu1', models.CharField(blank=True, max_length=10, null=True)),
                ('marca_maquina2', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo_maquina2', models.CharField(blank=True, max_length=50, null=True)),
                ('ppu2', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('id_proyecto', models.ForeignKey(db_column='id_proyecto', on_delete=django.db.models.deletion.CASCADE, to='administrador.proyectos', to_field='id')),
            ],
            options={
                'db_table': 'prospecciones',
            },
        ),
        migrations.CreateModel(
            name='Humedad',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('humedad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('profundidad_promedio', models.DecimalField(decimal_places=3, max_digits=12)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_prospeccion', models.CharField(blank=True, max_length=25, null=True)),
                ('id_prospeccion', models.ForeignKey(db_column='id_prospeccion', on_delete=django.db.models.deletion.CASCADE, to='administrador.prospecciones', to_field='id_prospeccion')),
                ('id_proyecto', models.ForeignKey(db_column='id_proyecto', on_delete=django.db.models.deletion.CASCADE, to='administrador.proyectos', to_field='id')),
            ],
            options={
                'db_table': 'humedad',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.proyectos')),
            ],
        ),
    ]
