# Generated by Django 5.1.4 on 2025-01-19 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.poll')),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_proyecto', models.CharField(choices=[('propuesta', 'Propuesta'), ('ejecucion', 'ejecucion'), ('standby', 'StandBy')], max_length=25, null=True)),
                ('id', models.CharField(max_length=25, unique=True)),
                ('pm', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('alcance', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proyectos',
            },
        ),
        migrations.CreateModel(
            name='Prospecciones',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_prospeccion', models.CharField(choices=[('sondajes', 'Sondajes'), ('calicatas', 'Calicatas'), ('geofisica', 'Geofísica')], max_length=25)),
                ('id_prospeccion', models.CharField(max_length=25, unique=True)),
                ('area', models.CharField(default='default_value', max_length=50)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('coordenada_este', models.CharField(blank=True, max_length=6, null=True)),
                ('coordenada_norte', models.CharField(blank=True, max_length=7, null=True)),
                ('elevacion', models.IntegerField(blank=True, null=True)),
                ('profundidad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('verificacion_puntos', models.CharField(blank=True, choices=[('realizado', 'Realizado'), ('no_realizado', 'No Realizado')], max_length=25, null=True)),
                ('plataforma', models.CharField(blank=True, choices=[('realizado', 'Realizado'), ('no_realizado', 'No Realizado')], max_length=25, null=True)),
                ('inclinacion', models.IntegerField(blank=True, null=True)),
                ('diametro', models.IntegerField(blank=True, null=True)),
                ('tapado', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=25, null=True)),
                ('contratista', models.CharField(blank=True, max_length=100, null=True)),
                ('marca_maquina1', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo_maquina1', models.CharField(blank=True, max_length=50, null=True)),
                ('ppu1', models.CharField(blank=True, max_length=10, null=True)),
                ('marca_maquina2', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo_maquina2', models.CharField(blank=True, max_length=50, null=True)),
                ('ppu2', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_proyecto', models.ForeignKey(db_column='id_proyecto', on_delete=django.db.models.deletion.CASCADE, to='administrador.proyectos', to_field='id')),
            ],
            options={
                'db_table': 'prospecciones',
            },
        ),
        migrations.CreateModel(
            name='Muestreo',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('id_embalaje', models.CharField(max_length=255)),
                ('tipo_prospeccion', models.CharField(blank=True, max_length=25, null=True)),
                ('area', models.CharField(max_length=50)),
                ('fecha_muestreo', models.DateField(blank=True, null=True)),
                ('tipo_embalaje', models.CharField(blank=True, choices=[('caja_nucleo', 'caja_nucleo'), ('bolsa_muestra', 'bolsa_muestra'), ('saco_muestra', 'saco_muestra'), ('tubo_pvc', 'tubo_pvc'), ('tambor', 'tambor')], max_length=25, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peso_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peso_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('id_muestra', models.CharField(max_length=50)),
                ('profundidad_desde', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('profundidad_hasta', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estrato', models.CharField(blank=True, choices=[('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3'), ('h4', 'h4'), ('h5', 'h5'), ('h6', 'h6'), ('h7', 'h7'), ('h8', 'h8')], max_length=25, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('perturbada', 'perturbada'), ('no_perturbada', 'no_perturbada'), ('colpa', 'colpa')], max_length=25, null=True)),
                ('fecha_despacho', models.DateField(blank=True, null=True)),
                ('nombre_despachador', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('orden_trasporte', models.CharField(max_length=50)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_prospeccion', models.ForeignKey(db_column='id_prospeccion', on_delete=django.db.models.deletion.CASCADE, related_name='muestreos_por_id', to='administrador.prospecciones', to_field='id_prospeccion')),
                ('id_proyecto', models.ForeignKey(db_column='id_proyecto', on_delete=django.db.models.deletion.CASCADE, to='administrador.proyectos', to_field='id')),
            ],
            options={
                'db_table': 'muestreo',
            },
        ),
        migrations.CreateModel(
            name='Humedad',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('humedad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('profundidad_promedio', models.DecimalField(decimal_places=3, max_digits=12)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_prospeccion', models.CharField(blank=True, max_length=25, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_prospeccion', models.ForeignKey(db_column='id_prospeccion', on_delete=django.db.models.deletion.CASCADE, to='administrador.prospecciones', to_field='id_prospeccion')),
                ('id_proyecto', models.ForeignKey(db_column='id_proyecto', on_delete=django.db.models.deletion.CASCADE, to='administrador.proyectos', to_field='id')),
            ],
            options={
                'db_table': 'humedad',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.proyectos')),
            ],
            options={
                'db_table': 'area',
            },
        ),
    ]
