# Generated by Django 5.1.4 on 2025-01-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestreo',
            name='destino',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='muestreo',
            name='nombre_despachador',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='muestreo',
            name='orden_trasporte',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospecciones',
            name='area',
            field=models.CharField(default='', max_length=50),
        ),
    ]
