# Generated by Django 5.0.13 on 2025-04-06 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmuestreo',
            name='estrato',
            field=models.CharField(blank=True, choices=[], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmuestreo',
            name='objetivo',
            field=models.CharField(blank=True, choices=[], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmuestreo',
            name='tipo',
            field=models.CharField(blank=True, choices=[], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmuestreo',
            name='tipo_embalaje',
            field=models.CharField(blank=True, choices=[], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='muestreo',
            name='estrato',
            field=models.CharField(blank=True, choices=[], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='muestreo',
            name='objetivo',
            field=models.CharField(blank=True, choices=[], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='muestreo',
            name='tipo',
            field=models.CharField(blank=True, choices=[], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='muestreo',
            name='tipo_embalaje',
            field=models.CharField(blank=True, choices=[], max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='MuestreoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='muestreo_images/%Y/%m/%d/')),
                ('muestreo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestreo_imagenes', to='administrador.muestreo')),
            ],
        ),
        migrations.AddField(
            model_name='muestreo',
            name='imagenes',
            field=models.ManyToManyField(blank=True, related_name='muestreos_con_imagen', to='administrador.muestreoimage'),
        ),
    ]
