# Generated by Django 5.1.4 on 2024-12-09 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_usuarios'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuarios',
            table='usuarios',
        ),
    ]
