# Generated by Django 5.1.4 on 2025-01-20 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_alter_muestreo_destino_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='programa',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('objetivo', models.CharField(blank=True, choices=[('clasificacion completa', 'clasificacion completa'), ('humedad', 'humedad'), ('sales solubles, cloruros y sulfatos', 'sales solubles, cloruros y sulfatos'), ('carbonatos', 'carbonatos'), ('triaxial ciu/cid 15x30 hasta 6kg cm2', 'triaxial ciu/cid 15x30 hasta 6kg cm2'), ('triaxial ciu/cid 15x30 hasta 9kg cm2', 'triaxial ciu/cid 15x30 hasta 9kg cm2'), ('granulometria', 'granulometria'), ('peso unitario', 'peso unitario'), ('difraccion de rayos x', 'difraccion de rayos x'), ('triaxial ciu/cid 5x10 hasta 6kg cm2', 'triaxial ciu/cid 5x10 hasta 6kg cm2'), ('triaxial ciu/cid 5x10 hasta 30kg cm2', 'triaxial ciu/cid 5x10 hasta 30kg cm2'), ('impurezas organicas', 'impurezas organicas'), ('sales solubles totales', 'sales solubles totales'), ('resistencia al desgaste, metodo los angeles', 'resistencia al desgaste, metodo los angeles'), ('densidad in situ', 'densidad in situ'), ('densidad aparente', 'densidad aparente'), ('resistencia a la desintegracion', 'resistencia a la desintegracion'), ('uscs', 'uscs'), ('triaxial ciu/cid 10x20 hasta 6kg cm2', 'triaxial ciu/cid 10x20 hasta 6kg cm2'), ('triaxial ciu/cid 10x20 hasta 12kg cm2', 'triaxial ciu/cid 10x20 hasta 12kg cm2'), ('densidad maxima y minima', 'densidad maxima y minima'), ('permeabilidad pared flexible carga constante (10x20 hasta 6 kg/cm2)', 'permeabilidad pared flexible carga constante (10x20 hasta 6 kg/cm2)'), ('permeabilidad pared flexible carga constante (15x30 hasta 6 kg/cm2)', 'permeabilidad pared flexible carga constante (15x30 hasta 6 kg/cm2)'), ('cbr', 'cbr'), ('slake durability', 'slake durability'), ('proctor modificado', 'proctor modificado'), ('corte directo', 'corte directo'), ('ph', 'ph'), ('determinacion de propiedades fisicas', 'determinacion de propiedades fisicas'), ('resistividad electrica', 'resistividad electrica'), ('compresion simple', 'compresion simple'), ('carga puntual', 'carga puntual'), ('traccion indirecta, metodo brasileno', 'traccion indirecta, metodo brasileno'), ('triaxial con medicion de deformacion axial y transversal', 'triaxial con medicion de deformacion axial y transversal')], max_length=255, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_ingreso_lab', models.DateField(blank=True, null=True)),
                ('id_ingreso', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('fecha_envio_programa', models.DateField(blank=True, null=True)),
                ('asignar_muestra', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_informe', models.DateField(blank=True, null=True)),
                ('n_informe', models.CharField(blank=True, max_length=50, null=True)),
                ('n_ep', models.CharField(blank=True, max_length=50, null=True)),
                ('id_prospeccion', models.ForeignKey(db_column='id_prospeccion', on_delete=django.db.models.deletion.CASCADE, to='administrador.prospecciones', to_field='id_prospeccion')),
                ('id_proyecto', models.ForeignKey(db_column='id_proyecto', on_delete=django.db.models.deletion.CASCADE, to='administrador.proyectos', to_field='id')),
            ],
        ),
    ]
