# Generated by Django 5.1.4 on 2024-12-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_alter_usuarios_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='correo',
            new_name='email',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='Empresa',
            field=models.CharField(default='No asignado', max_length=25),
            preserve_default=False,
        ),
    ]
