# Generated by Django 5.0.13 on 2025-04-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_alter_historicalmuestreo_estrato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muestreo',
            name='imagenes',
        ),
        migrations.AlterField(
            model_name='historicalmuestreo',
            name='estrato',
            field=models.CharField(blank=True, choices=[('h1', 'H1')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmuestreo',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('clasificacion completa', 'Clasificación completa')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmuestreo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('perturbada', 'Perturbada')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmuestreo',
            name='tipo_embalaje',
            field=models.CharField(blank=True, choices=[('caja_nucleo', 'Caja núcleo')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='muestreo',
            name='estrato',
            field=models.CharField(blank=True, choices=[('h1', 'H1')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='muestreo',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('clasificacion completa', 'Clasificación completa')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='muestreo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('perturbada', 'Perturbada')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='muestreo',
            name='tipo_embalaje',
            field=models.CharField(blank=True, choices=[('caja_nucleo', 'Caja núcleo')], max_length=25, null=True),
        ),
    ]
