# Generated by Django 5.1.4 on 2025-01-11 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_area_user_humedad_user_prospecciones_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospecciones',
            name='area',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Muestreo',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_muestreo', models.DateField(blank=True, null=True)),
                ('n_muestra', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('embalaje', models.CharField(blank=True, choices=[('caja_nucleo', 'caja_nucleo'), ('bolsa_muestra', 'bolsa_muestra'), ('saco_muestra', 'saco_muestra'), ('tubo_pvc', 'tubo_pvc'), ('tambor', 'tambor')], max_length=25, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cota_desde', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cota_hasta', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estrato', models.CharField(blank=True, choices=[('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3'), ('h4', 'h4'), ('h5', 'h5'), ('h6', 'h6'), ('h7', 'h7'), ('h8', 'h8')], max_length=25, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('perturbada', 'perturbada'), ('no_perturbada', 'no_perturbada'), ('colpa', 'colpa')], max_length=25, null=True)),
                ('area', models.CharField(max_length=50)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_prospeccion', models.CharField(max_length=25)),
                ('id_prospeccion', models.ForeignKey(db_column='id_prospeccion', on_delete=django.db.models.deletion.CASCADE, to='administrador.prospecciones', to_field='id_prospeccion')),
                ('id_proyecto', models.ForeignKey(db_column='id_proyecto', on_delete=django.db.models.deletion.CASCADE, to='administrador.proyectos', to_field='id')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'muestreo',
            },
        ),
    ]
