# Generated by Django 5.0.13 on 2025-04-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_remove_muestreo_imagenes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestreo',
            name='imagenes',
            field=models.ManyToManyField(blank=True, related_name='muestreos_con_imagen', to='administrador.muestreoimage'),
        ),
        migrations.AlterField(
            model_name='historicalmuestreo',
            name='estrato',
            field=models.CharField(blank=True, choices=[('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6'), ('h7', 'H7'), ('h8', 'H8')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmuestreo',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('clasificacion completa', 'Clasificación completa'), ('humedad', 'Humedad'), ('sales solubles, cloruros y sulfatos', 'Sales solubles, cloruros y sulfatos'), ('carbonatos', 'Carbonatos'), ('triaxial ciu/cid 15x30 hasta 6kg cm2', 'Triaxial CIU/CID 15x30 hasta 6kg/cm²'), ('triaxial ciu/cid 15x30 hasta 9kg cm2', 'Triaxial CIU/CID 15x30 hasta 9kg/cm²'), ('granulometria', 'Granulometría'), ('peso unitario', 'Peso unitario'), ('difraccion de rayos x', 'Difracción de rayos X'), ('triaxial ciu/cid 5x10 hasta 6kg cm2', 'Triaxial CIU/CID 5x10 hasta 6kg/cm²'), ('triaxial ciu/cid 5x10 hasta 30kg cm2', 'Triaxial CIU/CID 5x10 hasta 30kg/cm²'), ('impurezas organicas', 'Impurezas orgánicas'), ('sales solubles totales', 'Sales solubles totales'), ('resistencia al desgaste, metodo los angeles', 'Resistencia al desgaste, método Los Ángeles'), ('densidad in situ', 'Densidad in situ'), ('densidad aparente', 'Densidad aparente'), ('resistencia a la desintegracion', 'Resistencia a la desintegración'), ('uscs', 'USCS'), ('triaxial ciu/cid 10x20 hasta 6kg cm2', 'Triaxial CIU/CID 10x20 hasta 6kg/cm²'), ('triaxial ciu/cid 10x20 hasta 12kg cm2', 'Triaxial CIU/CID 10x20 hasta 12kg/cm²'), ('densidad maxima y minima', 'Densidad máxima y mínima'), ('permeabilidad pared flexible carga constante (10x20 hasta 6 kg/cm2)', 'Permeabilidad pared flexible carga constante (10x20 hasta 6 kg/cm²)'), ('permeabilidad pared flexible carga constante (15x30 hasta 6 kg/cm2)', 'Permeabilidad pared flexible carga constante (15x30 hasta 6 kg/cm²)'), ('cbr', 'CBR'), ('slake durability', 'Slake durability'), ('proctor modificado', 'Proctor modificado'), ('corte directo', 'Corte directo'), ('ph', 'pH'), ('determinacion de propiedades fisicas', 'Determinación de propiedades físicas'), ('resistividad electrica', 'Resistividad eléctrica'), ('compresion simple', 'Compresión simple'), ('carga puntual', 'Carga puntual'), ('traccion indirecta, metodo brasileno', 'Tracción indirecta, método brasileño'), ('triaxial con medicion de deformacion axial y transversal', 'Triaxial con medición de deformación axial y transversal')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmuestreo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('perturbada', 'Perturbada'), ('no_perturbada', 'No perturbada'), ('colpa', 'Colpa')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmuestreo',
            name='tipo_embalaje',
            field=models.CharField(blank=True, choices=[('caja_nucleo', 'Caja núcleo'), ('bolsa_muestra', 'Bolsa muestra'), ('saco_muestra', 'Saco muestra'), ('tubo_pvc', 'Tubo PVC'), ('caja_varias_muestras', 'Caja (para varias muestras)'), ('bins', 'Bins'), ('tambor', 'Tambor'), ('otro', 'Otro')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='muestreo',
            name='estrato',
            field=models.CharField(blank=True, choices=[('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6'), ('h7', 'H7'), ('h8', 'H8')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='muestreo',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('clasificacion completa', 'Clasificación completa'), ('humedad', 'Humedad'), ('sales solubles, cloruros y sulfatos', 'Sales solubles, cloruros y sulfatos'), ('carbonatos', 'Carbonatos'), ('triaxial ciu/cid 15x30 hasta 6kg cm2', 'Triaxial CIU/CID 15x30 hasta 6kg/cm²'), ('triaxial ciu/cid 15x30 hasta 9kg cm2', 'Triaxial CIU/CID 15x30 hasta 9kg/cm²'), ('granulometria', 'Granulometría'), ('peso unitario', 'Peso unitario'), ('difraccion de rayos x', 'Difracción de rayos X'), ('triaxial ciu/cid 5x10 hasta 6kg cm2', 'Triaxial CIU/CID 5x10 hasta 6kg/cm²'), ('triaxial ciu/cid 5x10 hasta 30kg cm2', 'Triaxial CIU/CID 5x10 hasta 30kg/cm²'), ('impurezas organicas', 'Impurezas orgánicas'), ('sales solubles totales', 'Sales solubles totales'), ('resistencia al desgaste, metodo los angeles', 'Resistencia al desgaste, método Los Ángeles'), ('densidad in situ', 'Densidad in situ'), ('densidad aparente', 'Densidad aparente'), ('resistencia a la desintegracion', 'Resistencia a la desintegración'), ('uscs', 'USCS'), ('triaxial ciu/cid 10x20 hasta 6kg cm2', 'Triaxial CIU/CID 10x20 hasta 6kg/cm²'), ('triaxial ciu/cid 10x20 hasta 12kg cm2', 'Triaxial CIU/CID 10x20 hasta 12kg/cm²'), ('densidad maxima y minima', 'Densidad máxima y mínima'), ('permeabilidad pared flexible carga constante (10x20 hasta 6 kg/cm2)', 'Permeabilidad pared flexible carga constante (10x20 hasta 6 kg/cm²)'), ('permeabilidad pared flexible carga constante (15x30 hasta 6 kg/cm2)', 'Permeabilidad pared flexible carga constante (15x30 hasta 6 kg/cm²)'), ('cbr', 'CBR'), ('slake durability', 'Slake durability'), ('proctor modificado', 'Proctor modificado'), ('corte directo', 'Corte directo'), ('ph', 'pH'), ('determinacion de propiedades fisicas', 'Determinación de propiedades físicas'), ('resistividad electrica', 'Resistividad eléctrica'), ('compresion simple', 'Compresión simple'), ('carga puntual', 'Carga puntual'), ('traccion indirecta, metodo brasileno', 'Tracción indirecta, método brasileño'), ('triaxial con medicion de deformacion axial y transversal', 'Triaxial con medición de deformación axial y transversal')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='muestreo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('perturbada', 'Perturbada'), ('no_perturbada', 'No perturbada'), ('colpa', 'Colpa')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='muestreo',
            name='tipo_embalaje',
            field=models.CharField(blank=True, choices=[('caja_nucleo', 'Caja núcleo'), ('bolsa_muestra', 'Bolsa muestra'), ('saco_muestra', 'Saco muestra'), ('tubo_pvc', 'Tubo PVC'), ('caja_varias_muestras', 'Caja (para varias muestras)'), ('bins', 'Bins'), ('tambor', 'Tambor'), ('otro', 'Otro')], max_length=25, null=True),
        ),
    ]
