# Generated by Django 5.1.4 on 2024-12-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_rename_correo_usuarios_email_usuarios_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='Empresa',
            new_name='empresa',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
