# Generated by Django 5.1.4 on 2025-01-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_programa_tipo_prospeccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='cantidad_recibida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
