# Generated by Django 5.1.4 on 2025-01-20 06:50

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_programa_cantidad_recibida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProspecciones',
            fields=[
                ('n', models.IntegerField(blank=True, db_index=True)),
                ('tipo_prospeccion', models.CharField(choices=[('sondajes', 'Sondajes'), ('calicatas', 'Calicatas'), ('geofisica', 'Geofísica')], max_length=25)),
                ('id_prospeccion', models.CharField(db_index=True, max_length=25)),
                ('area', models.CharField(default='', max_length=50)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('coordenada_este', models.CharField(blank=True, max_length=6, null=True)),
                ('coordenada_norte', models.CharField(blank=True, max_length=7, null=True)),
                ('elevacion', models.IntegerField(blank=True, null=True)),
                ('profundidad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('verificacion_puntos', models.CharField(blank=True, choices=[('realizado', 'Realizado'), ('no_realizado', 'No Realizado')], max_length=25, null=True)),
                ('plataforma', models.CharField(blank=True, choices=[('realizado', 'Realizado'), ('no_realizado', 'No Realizado')], max_length=25, null=True)),
                ('inclinacion', models.IntegerField(blank=True, null=True)),
                ('diametro', models.IntegerField(blank=True, null=True)),
                ('tapado', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=25, null=True)),
                ('contratista', models.CharField(blank=True, max_length=100, null=True)),
                ('marca_maquina1', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo_maquina1', models.CharField(blank=True, max_length=50, null=True)),
                ('ppu1', models.CharField(blank=True, max_length=10, null=True)),
                ('marca_maquina2', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo_maquina2', models.CharField(blank=True, max_length=50, null=True)),
                ('ppu2', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.TextField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_proyecto', models.ForeignKey(blank=True, db_column='id_proyecto', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administrador.proyectos', to_field='id')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical prospecciones',
                'verbose_name_plural': 'historical prospeccioness',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
