# Generated by Django 5.1.4 on 2024-12-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_proyectos_delete_agregado_remove_cafetam_codcafe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
