# Generated by Django 5.0.13 on 2025-04-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_alter_historicalmuestreo_peso_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmuestreo',
            name='id_embalaje',
        ),
        migrations.RemoveField(
            model_name='historicalmuestreo',
            name='tipo_embalaje',
        ),
        migrations.RemoveField(
            model_name='muestreo',
            name='id_embalaje',
        ),
        migrations.RemoveField(
            model_name='muestreo',
            name='tipo_embalaje',
        ),
        migrations.AddField(
            model_name='historicalmuestreo',
            name='id_bulto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalmuestreo',
            name='id_embalaje_muestra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalmuestreo',
            name='id_laboratorio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalmuestreo',
            name='tipo_bulto',
            field=models.CharField(blank=True, choices=[('pallets', 'Pallets'), ('caja_varias_muestras', 'Caja (para varias muestras)'), ('bins', 'Bins'), ('tambor', 'Tambor'), ('otro', 'Otro')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='historicalmuestreo',
            name='tipo_embalaje_muestra',
            field=models.CharField(blank=True, choices=[('caja_testigos', 'Caja testigos'), ('bolsa_muestra', 'Bolsa muestra'), ('saco_muestra', 'Saco muestra'), ('tubo_pvc', 'Tubo PVC'), ('otro', 'Otro')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='muestreo',
            name='id_bulto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='muestreo',
            name='id_embalaje_muestra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='muestreo',
            name='id_laboratorio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='muestreo',
            name='tipo_bulto',
            field=models.CharField(blank=True, choices=[('pallets', 'Pallets'), ('caja_varias_muestras', 'Caja (para varias muestras)'), ('bins', 'Bins'), ('tambor', 'Tambor'), ('otro', 'Otro')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='muestreo',
            name='tipo_embalaje_muestra',
            field=models.CharField(blank=True, choices=[('caja_testigos', 'Caja testigos'), ('bolsa_muestra', 'Bolsa muestra'), ('saco_muestra', 'Saco muestra'), ('tubo_pvc', 'Tubo PVC'), ('otro', 'Otro')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmuestreo',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('USCS', 'Clasificación completa (USCS)'), ('W', 'Humedad natural'), ('LIM', 'Límites'), ('GRA', 'Granulometría'), ('Gs', 'Peso específico de sólidos'), ('PF', 'Propiedades físicas (básicas)'), ('PM', 'Proctor modificado'), ('COMP', 'Proctor estándar'), ('DR', 'Densidad máxima y mínima'), ('DR_IN_SITU', 'Densidad in situ'), ('DR_APARENTE', 'Densidad aparente'), ('PU', 'Peso unitario'), ('CBR', 'Capacidad de soporte CBR'), ('CS', 'Compresión simple'), ('CD', 'Corte directo'), ('TX15_6', 'Triaxial CIU/CID 15x30 (6kg/cm²)'), ('TX15_9', 'Triaxial CIU/CID 15x30 (9kg/cm²)'), ('TX10_6', 'Triaxial CIU/CID 10x20 (6kg/cm²)'), ('TX10_12', 'Triaxial CIU/CID 10x20 (12kg/cm²)'), ('TIB', 'Tracción indirecta (Brasileño)'), ('CP', 'Carga puntual (roca)'), ('IC', 'Índice de compresibilidad'), ('CV', 'Consolidación (Edómetro)'), ('PER', 'Permeabilidad'), ('PPF_10x20', 'Permeabilidad pared flexible (10x20)'), ('PPF_15x30', 'Permeabilidad pared flexible (15x30)'), ('AA', 'Absorción de agua'), ('HL', 'Hinchamiento libre'), ('PHINCH', 'Presión de hinchamiento'), ('SS', 'Sales solubles totales'), ('CL', 'Cloruros'), ('SULF', 'Sulfatos'), ('CARB', 'Carbonatos'), ('PH', 'pH'), ('ABA', 'Balance ácido'), ('NAG', 'Generación de ácido neutralizado'), ('DS', 'Desintegración por sulfatos'), ('SD', 'Slake durability'), ('LA', 'Desgaste Los Ángeles'), ('RE', 'Resistividad eléctrica'), ('MT', 'Metales traza'), ('SPLP', 'Lixiviación SPLP'), ('STLC', 'Límite umbral soluble (STLC)'), ('DRX', 'Difracción de rayos X'), ('EQ', 'Equivalente de arena'), ('CE', 'Contracción por secado'), ('IO', 'Impurezas orgánicas'), ('TX_DEF', 'Triaxial con deformación axial/transversal')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='muestreo',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('USCS', 'Clasificación completa (USCS)'), ('W', 'Humedad natural'), ('LIM', 'Límites'), ('GRA', 'Granulometría'), ('Gs', 'Peso específico de sólidos'), ('PF', 'Propiedades físicas (básicas)'), ('PM', 'Proctor modificado'), ('COMP', 'Proctor estándar'), ('DR', 'Densidad máxima y mínima'), ('DR_IN_SITU', 'Densidad in situ'), ('DR_APARENTE', 'Densidad aparente'), ('PU', 'Peso unitario'), ('CBR', 'Capacidad de soporte CBR'), ('CS', 'Compresión simple'), ('CD', 'Corte directo'), ('TX15_6', 'Triaxial CIU/CID 15x30 (6kg/cm²)'), ('TX15_9', 'Triaxial CIU/CID 15x30 (9kg/cm²)'), ('TX10_6', 'Triaxial CIU/CID 10x20 (6kg/cm²)'), ('TX10_12', 'Triaxial CIU/CID 10x20 (12kg/cm²)'), ('TIB', 'Tracción indirecta (Brasileño)'), ('CP', 'Carga puntual (roca)'), ('IC', 'Índice de compresibilidad'), ('CV', 'Consolidación (Edómetro)'), ('PER', 'Permeabilidad'), ('PPF_10x20', 'Permeabilidad pared flexible (10x20)'), ('PPF_15x30', 'Permeabilidad pared flexible (15x30)'), ('AA', 'Absorción de agua'), ('HL', 'Hinchamiento libre'), ('PHINCH', 'Presión de hinchamiento'), ('SS', 'Sales solubles totales'), ('CL', 'Cloruros'), ('SULF', 'Sulfatos'), ('CARB', 'Carbonatos'), ('PH', 'pH'), ('ABA', 'Balance ácido'), ('NAG', 'Generación de ácido neutralizado'), ('DS', 'Desintegración por sulfatos'), ('SD', 'Slake durability'), ('LA', 'Desgaste Los Ángeles'), ('RE', 'Resistividad eléctrica'), ('MT', 'Metales traza'), ('SPLP', 'Lixiviación SPLP'), ('STLC', 'Límite umbral soluble (STLC)'), ('DRX', 'Difracción de rayos X'), ('EQ', 'Equivalente de arena'), ('CE', 'Contracción por secado'), ('IO', 'Impurezas orgánicas'), ('TX_DEF', 'Triaxial con deformación axial/transversal')], max_length=255, null=True),
        ),
    ]
