# Generated by Django 5.1.4 on 2025-01-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_historicalprospecciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprospecciones',
            name='coordenada_este',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprospecciones',
            name='coordenada_norte',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prospecciones',
            name='coordenada_este',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prospecciones',
            name='coordenada_norte',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
