# Generated by Django 5.1.4 on 2025-01-25 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0008_alter_humedad_id_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humedad',
            name='id_proyecto',
            field=models.ForeignKey(db_column='id_proyecto', on_delete=django.db.models.deletion.CASCADE, to='administrador.proyectos', to_field='id'),
        ),
    ]
